-- SPDX-License-Identifier: CC-BY-4.0
-- Copyright (c) 2025 EML Labs, CSE, University of Moratuwa
-- Licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

-------------------------------------------------------------------------------
-- Research Group : EML Labs,CSE, University of Moratuwa
-- Authors        : Weijith Wimalasiri, Yasantha Niroshan,Chathuranga Hettiarachchi
-- 
-- Create Date    : 23-12-2025
-- Design Name    : Template Testbench
-- Module Name    : tb_template.vhd
-- Project Name.  : PPG Peak Detection on FPGA
-- Target Devices : Basys3 / Artix-7
-- Tool Versions  : Vivado 2019.1
-- Description    : This is a template VHDL testbench file. Replace this description with the actual functionality of the testbench.
--
-- Dependencies    : None
--
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
--   - Designed for single-channel input
-------------------------------------------------------------------------------